package com.oa.workflow;
import com.fasterxml.jackson.databind.ObjectMapper;import com.oa.common.*;import com.oa.system.auth.CurrentUser;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import java.time.*;import java.util.*;
@Service
public class WorkflowService {
 private final JdbcTemplate jdbc;private final ObjectMapper mapper=new ObjectMapper();public WorkflowService(JdbcTemplate j){jdbc=j;}
 @Transactional public Map<String,Object> start(String code,Long applicant,String title,Map<String,Object> form,String bt,String bid){Map<String,Object>d=jdbc.queryForMap("SELECT * FROM wf_definition WHERE code=? AND status=1",code);String no="WF"+System.currentTimeMillis();String json;try{json=mapper.writeValueAsString(form);}catch(Exception e){throw new BizException("表单格式错误");}jdbc.update("INSERT INTO wf_instance(instance_no,definition_id,title,form_json,business_type,business_id,applicant_id,status,current_node_seq,submitted_at) VALUES(?,?,?,?,?,?,?,'RUNNING',1,CURRENT_TIMESTAMP)",no,d.get("ID"),title,json,bt,bid,applicant);Long iid=jdbc.queryForObject("SELECT id FROM wf_instance WHERE instance_no=?",Long.class,no);advance(iid,1,form);return jdbc.queryForMap("SELECT * FROM wf_instance WHERE id=?",iid);}
 private void advance(Long iid,int from,Map<String,Object> form){List<Map<String,Object>>ns=jdbc.queryForList("SELECT * FROM wf_node WHERE definition_id=(SELECT definition_id FROM wf_instance WHERE id=?) AND seq>=? ORDER BY seq",iid,from);for(Map<String,Object> n:ns){if(!condition(n.get("CONDITION_JSON"),form))continue;Long approver=resolve(iid,String.valueOf(n.get("APPROVER_TYPE")),n.get("APPROVER_REF"));if(approver==null)continue;jdbc.update("INSERT INTO wf_task(instance_id,node_seq,approver_user_id,status) VALUES(?,?,?,'PENDING')",iid,n.get("SEQ"),approver);jdbc.update("UPDATE wf_instance SET current_node_seq=? WHERE id=?",n.get("SEQ"),iid);return;}finish(iid,"APPROVED");}
 private boolean condition(Object c,Map<String,Object>form){if(c==null)return true;String s=String.valueOf(c);if(s.contains("\"days\"")){Object v=form.get("days");return v!=null&&Double.parseDouble(String.valueOf(v))>3;}return true;}
 private Long resolve(Long iid,String type,Object ref){Long applicant=jdbc.queryForObject("SELECT applicant_id FROM wf_instance WHERE id=?",Long.class,iid);if("USER".equals(type))return Long.valueOf(String.valueOf(ref));if("HR".equals(type))return one("HR");if("FINANCE".equals(type))return one("FINANCE");Map<String,Object> emp=jdbc.queryForMap("SELECT dept_id FROM hr_employee WHERE id=(SELECT employee_id FROM sys_user WHERE id=?)",applicant);Long dept=((Number)emp.get("DEPT_ID")).longValue();while(dept!=null){Long leader=jdbc.queryForObject("SELECT leader_employee_id FROM org_dept WHERE id=?",Long.class,dept);if(leader!=null){Long uid=jdbc.queryForObject("SELECT id FROM sys_user WHERE employee_id=? AND status=1",Long.class,leader);if(uid!=null&&!uid.equals(applicant))return uid;}dept=jdbc.queryForObject("SELECT parent_id FROM org_dept WHERE id=?",Long.class,dept);if(dept==null)break;}return one("MANAGER");}
 private Long one(String role){List<Long> x=jdbc.query("SELECT ur.user_id FROM sys_user_role ur JOIN sys_role r ON r.id=ur.role_id JOIN sys_user u ON u.id=ur.user_id WHERE r.code=? AND u.status=1",new Object[]{role},(rs,n)->rs.getLong(1));return x.isEmpty()?null:x.get(0);}
 @Transactional public void handle(Long task,Long user,String action,String comment){Map<String,Object>t=jdbc.queryForMap("SELECT * FROM wf_task WHERE id=? AND approver_user_id=? AND status='PENDING'",task,user);jdbc.update("UPDATE wf_task SET status=?,comment=?,handled_at=CURRENT_TIMESTAMP WHERE id=?",action,comment,task);Long iid=((Number)t.get("INSTANCE_ID")).longValue();if("REJECTED".equals(action)){finish(iid,"REJECTED");return;}int seq=((Number)t.get("NODE_SEQ")).intValue();Map<String,Object>i=jdbc.queryForMap("SELECT form_json FROM wf_instance WHERE id=?",iid);try{advance(iid,seq+1,mapper.readValue(String.valueOf(i.get("FORM_JSON")),Map.class));}catch(Exception e){finish(iid,"APPROVED");}}
 private void finish(Long id,String status){jdbc.update("UPDATE wf_instance SET status=?,finished_at=CURRENT_TIMESTAMP WHERE id=?",status,id);}
}
