package com.oa.oauth;
import com.oa.common.*;import com.oa.system.auth.*;import com.fasterxml.jackson.databind.ObjectMapper;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.http.*;import org.springframework.web.bind.annotation.*;import javax.servlet.http.*;import java.net.*;import java.nio.charset.StandardCharsets;import java.security.*;import java.time.*;import java.util.*;
@RestController @RequestMapping("/api/oauth")
public class OAuthController {
 private final JdbcTemplate jdbc;private final TokenService tokens;private final ObjectMapper mapper=new ObjectMapper();public OAuthController(JdbcTemplate j,TokenService t){jdbc=j;tokens=t;}
 @GetMapping("/authorize")public ResponseEntity<?> authorize(@RequestParam String response_type,@RequestParam String client_id,@RequestParam String redirect_uri,@RequestParam(required=false,defaultValue="openid profile")String scope,@RequestParam(required=false)String state,@RequestParam(required=false)String code_challenge,@RequestParam(required=false)String code_challenge_method,@RequestParam(required=false)String oa_token,HttpServletRequest request){
  TokenService.Principal p=tokens.parse(oa_token!=null?oa_token:bearer(request));if(p==null)return ResponseEntity.status(401).body(Collections.singletonMap("loginUrl","/login?redirect="+URLEncoder.encode(redirect_uri,StandardCharsets.UTF_8)));
  Map<String,Object> c=client(client_id);if(!contains(String.valueOf(c.get("REDIRECT_URIS")),redirect_uri))return ResponseEntity.badRequest().body(error("invalid_request","回调地址未登记"));String code=UUID.randomUUID().toString().replace("-","");jdbc.update("INSERT INTO oauth_authorization_code(code,client_id,user_id,redirect_uri,scope,code_challenge,code_challenge_method,expires_at,used) VALUES(?,?,?,?,?,?,?,DATEADD('MINUTE',10,CURRENT_TIMESTAMP),0)",code,client_id,p.getUserId(),redirect_uri,scope,code_challenge,code_challenge_method);String u=redirect_uri+(redirect_uri.contains("?")?"&":"?")+"code="+code+(state==null?"":"&state="+URLEncoder.encode(state,StandardCharsets.UTF_8));return ResponseEntity.ok(Collections.singletonMap("redirectUrl",u));
 }
 @PostMapping("/token")public ResponseEntity<?> token(@RequestParam Map<String,String> form,HttpServletRequest req){try{String cid=form.get("client_id"),secret=form.get("client_secret");String basic=req.getHeader("Authorization");if((cid==null||secret==null)&&basic!=null&&basic.startsWith("Basic ")){String x=new String(Base64.getDecoder().decode(basic.substring(6)),StandardCharsets.UTF_8);int i=x.indexOf(':');cid=x.substring(0,i);secret=x.substring(i+1);}Map<String,Object> c=client(cid);if(!PasswordHasher.verify(secret,String.valueOf(c.get("CLIENT_SECRET_HASH"))))return ResponseEntity.status(401).body(error("invalid_client","客户端认证失败"));String grant=form.get("grant_type");if("authorization_code".equals(grant))return ResponseEntity.ok(exchangeCode(form,cid));if("refresh_token".equals(grant))return ResponseEntity.ok(refresh(form.get("refresh_token"),cid,c));if("client_credentials".equals(grant))return ResponseEntity.ok(issue(null,cid,String.valueOf(c.get("SCOPES")),c));if("password".equals(grant)&&String.valueOf(c.get("GRANT_TYPES")).contains("password")){Map<String,Object>u=jdbc.queryForMap("SELECT id,username FROM sys_user WHERE username=? AND status=1",form.get("username"));if(!PasswordHasher.verify(form.get("password"),String.valueOf(jdbc.queryForObject("SELECT password_hash FROM sys_user WHERE id=?",Object.class,u.get("ID")))))throw new BizException("用户名或密码错误");return ResponseEntity.ok(issue(((Number)u.get("ID")).longValue(),cid,form.get("scope"),c));}return ResponseEntity.badRequest().body(error("unsupported_grant_type","不支持的授权类型"));}catch(Exception e){return ResponseEntity.badRequest().body(error("invalid_grant",e.getMessage()));}}
 @GetMapping("/userinfo")public ResponseEntity<?> userinfo(HttpServletRequest req){TokenService.Principal p=tokens.parse(bearer(req));if(p==null||!"oauth".equals(p.getType()))return ResponseEntity.status(401).body(error("invalid_token","访问令牌无效"));Map<String,Object>u=jdbc.queryForMap("SELECT u.id,u.username,u.real_name,u.employee_id,e.email,e.mobile,e.employee_no,e.dept_id,d.name dept_name FROM sys_user u LEFT JOIN hr_employee e ON e.id=u.employee_id LEFT JOIN org_dept d ON d.id=e.dept_id WHERE u.id=?",p.getUserId());Map<String,Object>o=new LinkedHashMap<String,Object>();o.put("sub",p.getUserId());o.put("username",u.get("USERNAME"));o.put("name",u.get("REAL_NAME"));o.put("email",u.get("EMAIL"));o.put("mobile",u.get("MOBILE"));o.put("employeeNo",u.get("EMPLOYEE_NO"));o.put("deptId",u.get("DEPT_ID"));o.put("deptName",u.get("DEPT_NAME"));o.put("roles",jdbc.queryForList("SELECT r.code FROM sys_role r JOIN sys_user_role ur ON ur.role_id=r.id WHERE ur.user_id=?",p.getUserId()));return ResponseEntity.ok(o);}
 @PostMapping("/introspect")public Map<String,Object> introspect(@RequestParam String token){TokenService.Principal p=tokens.parse(token);Map<String,Object>o=new LinkedHashMap<String,Object>();o.put("active",p!=null&&"oauth".equals(p.getType()));if(p!=null){o.put("sub",p.getUserId());o.put("client_id",p.getClaims().get("cid"));o.put("exp",((Number)p.getClaims().get("exp")).longValue()/1000);}return o;}
 @PostMapping("/revoke")public Map<String,Object> revoke(@RequestParam String token){jdbc.update("UPDATE oauth_token SET revoked=1 WHERE access_token=? OR refresh_token=?",token,token);return Collections.singletonMap("revoked",true);}
 @GetMapping("/clients")public R<List<Map<String,Object>>> clients(){return R.ok(jdbc.queryForList("SELECT id,client_id,client_name,redirect_uris,grant_types,scopes,status FROM oauth_client"));}
 @RequestMapping(value="/clients",method={RequestMethod.POST,RequestMethod.PUT})public R<Map<String,Object>> saveClient(@RequestBody Map<String,Object>b){String secret=String.valueOf(b.getOrDefault("clientSecret",UUID.randomUUID().toString()));if(b.get("id")==null)jdbc.update("INSERT INTO oauth_client(client_id,client_secret_hash,client_name,redirect_uris,grant_types,scopes,status) VALUES(?,?,?,?,?,?,1)",b.get("clientId"),PasswordHasher.hash(secret),b.get("clientName"),b.get("redirectUris"),b.getOrDefault("grantTypes","authorization_code,refresh_token"),b.getOrDefault("scopes","openid profile"));else jdbc.update("UPDATE oauth_client SET client_name=?,redirect_uris=?,grant_types=?,scopes=? WHERE id=?",b.get("clientName"),b.get("redirectUris"),b.get("grantTypes"),b.get("scopes"),b.get("id"));return R.ok(Collections.singletonMap("clientSecret",secret));}
 private Map<String,Object> exchangeCode(Map<String,String>f,String cid){Map<String,Object>x=jdbc.queryForMap("SELECT * FROM oauth_authorization_code WHERE code=? AND client_id=? AND used=0 AND expires_at>CURRENT_TIMESTAMP",f.get("code"),cid);if(f.get("redirect_uri")!=null&&!f.get("redirect_uri").equals(x.get("REDIRECT_URI")))throw new BizException("回调地址不一致");String challenge=String.valueOf(x.get("CODE_CHALLENGE"));if(challenge!=null&&!challenge.equals("null")){String v=f.get("code_verifier");if(v==null||!challenge.equals(b64(sha(v))))throw new BizException("PKCE校验失败");}jdbc.update("UPDATE oauth_authorization_code SET used=1 WHERE id=?",x.get("ID"));return issue(((Number)x.get("USER_ID")).longValue(),cid,String.valueOf(x.get("SCOPE")),client(cid));}
 private Map<String,Object> refresh(String rt,String cid,Map<String,Object>c){Map<String,Object>x=jdbc.queryForMap("SELECT * FROM oauth_token WHERE refresh_token=? AND client_id=? AND revoked=0 AND refresh_expires_at>CURRENT_TIMESTAMP",rt,cid);jdbc.update("UPDATE oauth_token SET revoked=1 WHERE id=?",x.get("ID"));return issue(((Number)x.get("USER_ID")).longValue(),cid,String.valueOf(x.get("SCOPE")),c);}
 private Map<String,Object> issue(Long uid,String cid,String scope,Map<String,Object>c){int ttl=((Number)c.get("ACCESS_TOKEN_TTL")).intValue();String at=tokens.issueOAuth(uid,uid==null?"client":jdbc.queryForObject("SELECT username FROM sys_user WHERE id=?",String.class,uid),cid,ttl*1000L);String rt=UUID.randomUUID().toString();if(uid!=null)jdbc.update("INSERT INTO oauth_token(access_token,refresh_token,client_id,user_id,scope,access_expires_at,refresh_expires_at,revoked) VALUES(?,?,?,?,?,DATEADD('SECOND',?,CURRENT_TIMESTAMP),DATEADD('SECOND',?,CURRENT_TIMESTAMP),0)",at,rt,cid,uid,scope,ttl,((Number)c.get("REFRESH_TOKEN_TTL")).intValue());Map<String,Object>o=new LinkedHashMap<String,Object>();o.put("access_token",at);o.put("token_type","Bearer");o.put("expires_in",ttl);o.put("refresh_token",rt);o.put("scope",scope);return o;}
 private Map<String,Object>client(String id){return jdbc.queryForMap("SELECT * FROM oauth_client WHERE client_id=? AND status=1",id);}private boolean contains(String csv,String x){for(String s:csv.split(","))if(s.trim().equals(x))return true;return false;}private Map<String,String>error(String a,String b){Map<String,String>m=new HashMap<String,String>();m.put("error",a);m.put("error_description",b);return m;}private String bearer(HttpServletRequest r){String h=r.getHeader("Authorization");return h!=null&&h.regionMatches(true,0,"Bearer ",0,7)?h.substring(7):null;}private static byte[]sha(String s){try{return MessageDigest.getInstance("SHA-256").digest(s.getBytes(StandardCharsets.US_ASCII));}catch(Exception e){throw new IllegalStateException(e);}}private static String b64(byte[]b){return Base64.getUrlEncoder().withoutPadding().encodeToString(b);}
}
