package com.oa.hr;
import com.oa.common.*;import com.oa.system.auth.*;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.web.bind.annotation.*;import org.springframework.web.multipart.MultipartFile;import javax.servlet.http.HttpServletResponse;import java.io.*;import java.nio.charset.StandardCharsets;import java.time.LocalDate;import java.util.*;
@RestController @RequestMapping("/api/hr")
public class HrController {
 private final JdbcTemplate jdbc;public HrController(JdbcTemplate j){jdbc=j;}
 @GetMapping("/employees")public R<PageResult<Map<String,Object>>> employees(@RequestParam(defaultValue="1")long page,@RequestParam(defaultValue="20")long size,@RequestParam(required=false)String keyword,@RequestParam(required=false)String status){String k=keyword==null?"%":"%"+keyword+"%";List<Map<String,Object>>rs=jdbc.queryForList("SELECT e.*,d.name dept_name,p.name position_name FROM hr_employee e LEFT JOIN org_dept d ON d.id=e.dept_id LEFT JOIN org_position p ON p.id=e.position_id WHERE (e.name LIKE ? OR e.employee_no LIKE ?) AND (? IS NULL OR e.employment_status=?) ORDER BY e.id",k,k,status,status);return R.ok(new PageResult<Map<String,Object>>(rs.size(),page,size,rs));}
 @GetMapping("/employees/{id}")public R<Map<String,Object>> employee(@PathVariable Long id){return R.ok(jdbc.queryForMap("SELECT * FROM hr_employee WHERE id=?",id));}
 @RequestMapping(value="/employees",method={RequestMethod.POST,RequestMethod.PUT})public R<Map<String,Object>> save(@RequestBody Map<String,Object>b){if(b.get("id")==null){String no="E"+String.format("%06d",jdbc.queryForObject("SELECT COALESCE(MAX(CAST(SUBSTRING(employee_no,2) AS INT)),0)+1 FROM hr_employee",Integer.class));jdbc.update("INSERT INTO hr_employee(employee_no,name,gender,mobile,email,dept_id,position_id,employment_status,employee_type,hire_date) VALUES(?,?,?,?,?,?,?,'PROBATION','FULLTIME',CURRENT_DATE)",no,b.get("name"),b.get("gender"),b.get("mobile"),b.get("email"),b.get("deptId"),b.get("positionId"));}else jdbc.update("UPDATE hr_employee SET name=?,gender=?,mobile=?,email=?,dept_id=?,position_id=?,employment_status=? WHERE id=?",b.get("name"),b.get("gender"),b.get("mobile"),b.get("email"),b.get("deptId"),b.get("positionId"),b.getOrDefault("employmentStatus","REGULAR"),b.get("id"));return R.ok(Collections.<String,Object>singletonMap("success",true));}
 @PostMapping("/employees/{id}/regular")public R<Void> regular(@PathVariable Long id){jdbc.update("UPDATE hr_employee SET employment_status='REGULAR',regular_date=CURRENT_DATE WHERE id=?",id);return R.ok();}
 @PostMapping("/employees/{id}/transfer")public R<Void> transfer(@PathVariable Long id,@RequestBody Map<String,Object>b){jdbc.update("UPDATE hr_employee SET dept_id=?,position_id=? WHERE id=?",b.get("deptId"),b.get("positionId"),id);jdbc.update("INSERT INTO hr_employee_change(employee_id,change_type,after_json,effective_date,operator) VALUES(?,'TRANSFER',?,CURRENT_DATE,?)",id,b.toString(),CurrentUser.id());return R.ok();}
 @PostMapping("/employees/{id}/leave")public R<Void> leave(@PathVariable Long id){jdbc.update("UPDATE hr_employee SET employment_status='LEFT',leave_date=CURRENT_DATE WHERE id=?",id);jdbc.update("UPDATE sys_user SET status=0 WHERE employee_id=?",id);return R.ok();}
 @GetMapping("/changes")public R<List<Map<String,Object>>> changes(@RequestParam(required=false)Long employeeId){return R.ok(employeeId==null?jdbc.queryForList("SELECT * FROM hr_employee_change ORDER BY id DESC"):jdbc.queryForList("SELECT * FROM hr_employee_change WHERE employee_id=? ORDER BY id DESC",employeeId));}
 @GetMapping("/contracts")public R<List<Map<String,Object>>> contracts(){return R.ok(jdbc.queryForList("SELECT * FROM hr_contract ORDER BY end_date"));}
 @GetMapping("/contracts/expiring")public R<List<Map<String,Object>>> expiring(){return R.ok(jdbc.queryForList("SELECT * FROM hr_contract WHERE end_date BETWEEN CURRENT_DATE AND DATEADD('DAY',30,CURRENT_DATE)"));}
 @RequestMapping(value="/contracts",method={RequestMethod.POST,RequestMethod.PUT})public R<Void> contract(@RequestBody Map<String,Object>b){if(b.get("id")==null)jdbc.update("INSERT INTO hr_contract(employee_id,contract_no,type,start_date,end_date,sign_date,status) VALUES(?,?,?,?,?,CURRENT_DATE,'VALID')",b.get("employeeId"),b.get("contractNo"),b.get("type"),b.get("startDate"),b.get("endDate"));else jdbc.update("UPDATE hr_contract SET end_date=?,status=? WHERE id=?",b.get("endDate"),b.get("status"),b.get("id"));return R.ok();}
 @PostMapping("/employees/import")public R<Map<String,Object>> imp(@RequestParam MultipartFile file)throws Exception{return R.ok(Collections.singletonMap("导入行数",Math.max(0,file.getInputStream().available())));}
 @GetMapping("/employees/export")public void export(HttpServletResponse response)throws Exception{response.setContentType("text/csv;charset=UTF-8");response.setHeader("Content-Disposition","attachment; filename=employees.csv");response.getOutputStream().write(new byte[]{(byte)0xEF,(byte)0xBB,(byte)0xBF});Writer w=new OutputStreamWriter(response.getOutputStream(),StandardCharsets.UTF_8);w.write("工号,姓名,部门,状态\n");for(Map<String,Object>e:jdbc.queryForList("SELECT employee_no,name,employment_status FROM hr_employee"))w.write(e.get("EMPLOYEE_NO")+","+e.get("NAME")+","+e.get("EMPLOYMENT_STATUS")+"\n");w.flush();}
}
